from pathlib import Path
import gzip

import dmux.tools as dt

DATA_DIR = Path(__file__).parent / "data"

def test_fastq_parser():
    with gzip.open(DATA_DIR / "R1.fastq.gz", "rt") as r1:
        record = next(dt.fastq_parser(r1))
        
        assert len(record) == 4, (
            "Incorrect number of lines in a record generated by fastq_parser()."
        )
        assert record[0] == "@K00337:83:HJKJNBBXX:8:1101:1265:1191 1:N:0:1", (
            "Header from fastq_parser() does not match the expected string."
        )
        assert record[1] == "GCTGGCATTCCCAGAGACATCAGTACCCAGTTGGTTCAGACAGTTCCTCTATTGGTTGACAAGGTCTTCATTTCTAGTGATATCAACACGGTGTCTACAA", (
            "Sequence from fastq_parser() does not match the expected string."
        )
        assert record[2] == "+", (
            "Plus line from fastq_parser() does not match the expected string."
        )
        assert record[3] == "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ", (
            "Quality score from fastq_parser() does not match the expected string."
        )

def test_reverse_complement():
    seqs = [
        "GTAGCGTA",
        "AACAGCGA",
        "CGATNGAT",
        "CGAYCGAT",
        "NNNNNNNN"
    ]

    assert dt.reverse_complement(seqs[0]) == "TACGCTAC"
    assert dt.reverse_complement(seqs[1]) == "TCGCTGTT"
    assert dt.reverse_complement(seqs[2]) == "ATCNATCG"
    assert dt.reverse_complement(seqs[4]) == "NNNNNNNN"

    try:
        dt.reverse_complement(seqs[3])
        assert False, "ValueError was not raised."
    
    except ValueError:
        assert True

def test_create_new_header():
    with gzip.open(DATA_DIR / "R1.fastq.gz", "rt") as r1, gzip.open(DATA_DIR / "R2.fastq.gz", "rt") as i1, gzip.open(DATA_DIR / "R3.fastq.gz", "rt") as i2:
        read1 = next(dt.fastq_parser(r1))
        index1 = next(dt.fastq_parser(i1))
        index2 = next(dt.fastq_parser(i2))
        header = read1[0]
        ind1 = index1[1]
        ind2 = index2[1]
        rc_ind2 = dt.reverse_complement(ind2)

        result_match = dt.create_new_header(header, ind1, rc_ind2)
        result_mismatch = dt.create_new_header(header, ind1, ind2)

        assert result_match == "@K00337:83:HJKJNBBXX:8:1101:1265:1191 1:N:0:1 GTAGCGTA-GTAGCGTA"
        assert result_mismatch == "@K00337:83:HJKJNBBXX:8:1101:1265:1191 1:N:0:1 GTAGCGTA-TACGCTAC"

def test_write_record_to_file(tmp_path: str):
    output_file_path = Path(tmp_path) / "test_output.fastq.gz"

    with gzip.open(output_file_path, "wt") as fh:
        dt.write_record_to_file(
            output_file_handle=fh,
            new_header="header",
            sequence="sequence",
            plus_line="+",
            qscores="quality scores"
        )
    
    with gzip.open(output_file_path, "rt") as fh:
        assert sum(1 for _ in fh) > 0, "write_record_to_file output file is empty."
        assert sum(1 for _ in fh) == 4, "write_record_to_file output file does not have the expected number of lines."
